global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ipfs-gateway'
    static_configs:
      - targets: ['gateway:5050']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /stub_status
